name: Generate arcade animation

on:
  schedule:
    # Eksekusi otomatis setiap 12 jam
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      # Langkah 1: Checkout repositori
      - uses: actions/checkout@v3

      # Langkah 2: Bikin grafik kontribusi bertema Pacman asli
      - name: generate pacman-contribution-graph.svg
        uses: abbozanona/pacman-contribution-graph@main
        with:
          github_user_name: NikmalWahid22
          games: 'pacman'

      # Langkah 3: Amankan dan simpan hasilnya ke branch pacman-output
      - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: pacman-output
          build_dir: . # Mengarah ke root tempat file pacman digenerate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
