name: Generate arcade 3d animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Langkah 1: Ambil kode repo dengan versi terbaru
      - uses: actions/checkout@v4

      # Langkah 2: Bikin grafik kontribusi 3D Isometric ala Retro Game
      - uses: joshcavanagh/github-contribution-3d@main
        with:
          github_user_name: NikmalWahid22

      # Langkah 3: Simpan hasilnya otomatis ke branch pacman-output
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: pacman-output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
